//path : model/hop-model/hop-contrainte.ts
export const constraints = {
    Version: { type: 'number' },
    TypFic: { type: 'text' },
    NomFic: { type: 'text' },
    DteStr: { type: 'date' },
    IdPost: { type: 'number' },
    LibellePoste: { type: 'text' },
    IdColl: { type: 'number' },
    FinJur: { type: 'text' },
    CodCol: { type: 'number' },
    CodBud: { type: 'number' },
    LibelleColBud: { type: 'text' },
    Exer: { type: 'number' },
    IdBord: { type: 'number' },
    TypBord: { type: 'number' },
    NbrePce: { type: 'number', pattern: '^[0-9]$', min: 0 },
    IdPce: { type: 'number' },
    TypPce: { type: 'number' },
    NatPce: { type: 'number' },
    CatPce: { type: 'number' },
    DebFact: { type: 'date' },
    FinFact: { type: 'date' },
    EtatPce: { type: 'text', pattern: '^(01|02)$' },
    DtePcePec: { type: 'date' },
    IdLigne: { type: 'number' },
    ObjLignePce: { type: 'text' },
    Nature: { type: 'number' },
    MtTTC: { type: 'number', step: '0.01' },
    DteMalade: { type: 'date' },
    RefTiers: { type: 'number' },
    CatTiers: { type: 'number' },
    TypTiers: { type: 'number' },
    Civilite: { type: 'text', pattern: '(MME|MR)', maxlength: 3 },
    Nom: { type: 'text' },
    Prenom: { type: 'text' },
    Adr1: { type: 'text' },
    Adr2: { type: 'text' },
    Adr3: { type: 'text' },
    CP: { type: 'number', pattern: '^[0-9]{5}$' },
    Ville: { type: 'text' },
  };
  